homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lake_latitude
  longitude: !secret lake_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 518
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  temperature_unit: F
  customize: !include customize.yaml
#  whitelist_external_dirs:
#    /home/homeassistant/.aws
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_api_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# iOS
ios:

automation: !include automations.yaml
script: !include scripts.yaml

group: !include groups.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
  terminal:
    title: Terminal
    icon: mdi:console
    url: https://hassio.local:7681
  logviewer:
    title: Log Viewer
    icon: mdi:message-text
    url: https://hassio.local:4277
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://hassio.local:3000
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: https://hassio.local:8888
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: https://hassio.local:1880

zone:
  name: Lake
  latitude: !secret lake_latitude
  longitude: !secret lake_longitude
  radius: 200
  icon: mdi:home

zone 2:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 200
  icon: mdi:home
  
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

mqtt:
  broker: !secret mqtt_broker
  port: 8883
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  certificate: /etc/ssl/certs/ca-certificates.crt
  protocol: 3.1.1
  tls_version: '1.2'

mqtt_statestream:
  base_topic: homeassistant

sensor:
# Weather prediction
  - platform: yr
  - platform: speedtest
    server_id: 1782
    minute:
    - 0
    - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: pollen
    zip_code: !secret lake_zip_code
    monitored_conditions:
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
    - disease_average_forecasted
  - platform: wunderground
    api_key: !secret wunderground_api_key
    pws_id: !secret wunderground_pws_id
    monitored_conditions:
      - station_id
      - precip_today_in
      - pressure_in
      - pressure_trend
      - relative_humidity
      - temp_high_record_f
      - temp_high_1d_f
      - temp_f
      - temp_low_1d_f
      - temp_low_record_f
      - precip_1d
      - precip_1d_mm
      - UV
      - visibility_mi
      - weather_1h
      - wind_degrees
      - wind_dir
      - wind_mph
      - wind_1d_mph
      - alerts
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
    show_on_map: false
    scan_interval: 600
  - platform: template
    sensors:
      living_room_lake:
        value_template: '{{ states.remote.living_room_lake.attributes.current_activity }}'
        friendly_name: 'Living Room'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: load_1m
      - type: load_5m 
      - type: load_15m
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  - platform: time_date
    display_options:
      - 'date_time'
  - platform: travisci
    api_key: !secret travisci_api_key
    repository: HomeAssistantConfig
      
vera:
  vera_controller_url: !secret vera_controller_url
  
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster

notify:
  - platform: ios
  - platform: hangouts
    name: !secret hangouts_name
    default_conversations:
      - id: homeassistant
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    name: pushbullet
  - platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: nfandroidtv
    name: NvidiaShield
    host: 192.168.200.28

abode:
  username: !secret abode_username
  password: !secret abode_username

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
#  structure:
#    - Lake

axis:
  p1440le1:
    host: 192.168.200.210
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - pir
      - sound
      - daynight
      - vmd3
      - tampering
    location: Main House Front Stairs
  p1440le2:
    host: 192.168.200.213
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - pir
      - sound
      - daynight
      - vmd3
      - tampering
    location: Main House Lake
  q6035e:
    host: 192.168.200.128
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - pir
      - vmd3
      - tampering
  m2014e1:
    host: 192.168.200.123
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - tampering
    location: Main House North Stairs
  m2014e2:
    host: 192.168.200.166
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - tampering
    location: Main House Front Door
  m5014:
    host: 192.168.200.217
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - tampering
    location: Garage Main Entry
  m1054:
    host: 192.168.200.164
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - sound
      - pir
      - tampering
    location: Main House Interior Entry

camera:
  - platform: ffmpeg
    name: South Yard
    input: -rtsp_transport tcp -i !secret camera_south_yard_rtsp_uri
  - platform: ffmpeg
    name: Driveway 1
    input: -rtsp_transport tcp -i !secret camera_driveway_1_rtsp_uri
    extra_arguments: -q:v 1 -r 30
  - platform: ffmpeg
    name: Driveway 2
    input: -rtsp_transport tcp -i !secret camera_driveway_2_rtsp_uri
    extra_arguments: -q:v 1 -r 30 
  - platform: ffmpeg
    name: Driveway 3
    input: -rtsp_transport tcp -i !secret camera_driveway_3_rtsp_uri
    extra_arguments: -q:v 1 -r 30
  - platform: ffmpeg
    name: South Gate
    input: -rtsp_transport tcp -i !secret camera_south_gate_rtsp_uri
  - platform: ffmpeg
    name: Garage South Fenceline
    input: -rtsp_transport tcp -i !secret camera_south_fenceline_rtsp_uri
    extra_arguments: -pred 1 # -q:v 2
  - platform: ffmpeg
    name: Main Gate
    input: -rtsp_transport tcp -i !secret camera_main_gate_rtsp_uri
  - platform: ffmpeg
    name:  Main House South Deck
    input: -rtsp_transport tcp -i !secret camera_main_house_south_deck_rtsp_uri

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true
    mqtt_topic: "owntracks/#"
    events_only: false
  - platform: gpslogger
    password: !secret gpslogger_password
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    account_name: !secret icloud_account_name

rachio:
  api_key: !secret rachio_api_key

tesla:
  username: !secret tesla_username
  password: !secret tesla_password

zwave:
  usb_path: /dev/ttyACM0