homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lake_latitude
  longitude: !secret lake_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 518
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  temperature_unit: F
  customize: !include customize.yaml
#  whitelist_external_dirs:
#    /home/homeassistant/.aws
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret http_api_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  enable:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# iOS
ios:

# Homekit Support
homekit:

automation: !include automations.yaml
script: !include scripts.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
zone: !include zones.yaml

panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: mdi:wrench
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: hassio-main
    sidebar_title: Log Viewer
    sidebar_icon: mdi:message-text
    js_url: /api/hassio/app/entrypoint.js
    url_path: logviewer
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_logviewer
  - name: hassio-main
    sidebar_title: InfluxDB
    sidebar_icon: mdi:chart-areaspline
    js_url: /api/hassio/app/entrypoint.js
    url_path: influxdb
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_influxdb
  - name: hassio-main
    sidebar_title: Node-Red
    sidebar_icon: mdi:sitemap
    js_url: /api/hassio/app/entrypoint.js
    url_path: nodered
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_nodered
  - name: hassio-main
    sidebar_title: Portainer
    sidebar_icon: mdi:docker
    js_url: /api/hassio/app/entrypoint.js
    url_path: portainer
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_portainer
  - name: hassio-main
    sidebar_title: Glances
    sidebar_icon: mdi:speedometer
    js_url: /api/hassio/app/entrypoint.js
    url_path: glances
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_glances
  - name: hassio-main
    sidebar_title: Terminal
    sidebar_icon: mdi:console
    js_url: /api/hassio/app/entrypoint.js
    url_path: ssh
    embed_iframe: true
    require_admin: true
    config:
      ingress: a0d7b954_ssh

panel_iframe:
#   configurator:
#     title: Configurator
#     icon: mdi:wrench
#     url: https://hassio.local:8123/api/hassio_ingress/gR8fNPLP7AshRxdPRlvcqXUkXfkp63J4cILmfFUjNyw/
#   terminal:
#     title: Terminal
#     icon: mdi:console
#     url: https://hassio.local:7681
#   logviewer:
#     title: Log Viewer
#     icon: mdi:message-text
#     url: https://hassio.local:4277
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: https://hassio.local:3000
#   influxdb:
#     title: InfluxDB
#     icon: mdi:chart-areaspline
#     url: https://hassio.local:8888
#   nodered:
#     title: Node-RED
#     icon: mdi:sitemap
#     url: https://hassio.local:1880
#   portainer:
#     title: Portainer
#     icon: mdi:docker
#     url: https://hassio.local:9000

#influxdb:
#  host: localhost
#  port: 8086
#  database: homeassistant
#  username: homeassistant
#  password: !secret influxdb_password
#  max_retries: 3
#  default_measurement: state

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

# mqtt:
#   broker: !secret mqtt_broker
#   port: 8883
#   client_id: homeassistant
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   certificate: /etc/ssl/certs/ca-certificates.crt
#   protocol: 3.1.1
#   tls_version: '1.2'

# mqtt_statestream:
#   base_topic: homeassistant

binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptime_robot_api_key

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_month_all_earthquakes'
    radius: 30
    minimum_magnitude: 0.0

openuv:
  api_key: !secret openuv_api_key
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6

vera:
  vera_controller_url: !secret vera_controller_url
  exclude: [ 9, 10, 11, 12, 17, 21, 23, 54, 55, 56, 61, 62, 63, 64, 94, 95, 96, 100, 101, 105, 107, 115, 117, 123, 124, 140, 142, 144, 146, 147, 148, 151, 155, 168, 176, 177, 179, 183, 184, 186, 191, 196, 201, 207, 213, 214, 215, 223, 224, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 238, 240, 241, 243, 246, 247 ]
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [ 74, 76, 78, 120, 133, 134, 135, 136, 160, 164, 167 ]

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster

notify:
  - platform: ios
  - platform: hangouts
    name: !secret hangouts_name
    default_conversations:
      - id: homeassistant
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    name: pushbullet
  - platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: nfandroidtv
    name: NvidiaShield
    host: 192.168.200.28

abode:
  username: !secret abode_username
  password: !secret abode_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  structure:
    - Lake

stream:

axis:
  p1440le1:
    host: 192.168.200.126
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - pir
      - sound
      - daynight
      - vmd3
      - tampering
    location: Main House Front Stairs
  p1440le2:
    host: 192.168.200.131
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - pir
      - sound
      - daynight
      - vmd3
      - tampering
    location: Main House Lake
  q6035e:
    host: 192.168.200.129
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - pir
      - vmd3
      - tampering
  m2014e1:
    host: 192.168.200.164
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - tampering
    location: Main House North Stairs
  m2014e2:
    host: 192.168.200.120
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - tampering
    location: Main House Front Door
  m5014:
    host: 192.168.200.128
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - tampering
    location: Garage Main Entry
  m1054:
    host: 192.168.200.123
    username: !secret axis_camera_username
    password: !secret axis_camera_password
    include:
      - camera
      - motion
      - sound
      - pir
      - tampering
    location: Main House Interior Entry

camera:
#  - platform: ffmpeg
#    name: South Yard
#    input: !secret camera_south_yard_rtsp_uri
#    extra_arguments: -q:v 1 -r 30
#  - platform: ffmpeg
#    name: Driveway 1
#    input: !secret camera_driveway_1_rtsp_uri
#    extra_arguments: -q:v 1 -r 30
  - platform: ffmpeg
    name: Driveway 2
    input: !secret camera_driveway_2_rtsp_uri
    extra_arguments: -q:v 1 -r 30 
#  - platform: ffmpeg
#    name: Driveway 3
#    input: !secret camera_driveway_3_rtsp_uri
#    extra_arguments: -q:v 1 -r 30
#  - platform: ffmpeg
#    name: South Gate
#    input: !secret camera_south_gate_rtsp_uri
#  - platform: ffmpeg
#    name: Garage South Fenceline
#    input: !secret camera_south_fenceline_rtsp_uri
#    extra_arguments: -q:v 1 -r 30
  - platform: ffmpeg
    name: Main Gate
    input: !secret camera_main_gate_rtsp_uri
  - platform: ffmpeg
    name:  Main House South Deck
    input: !secret camera_main_house_south_deck_rtsp_uri

device_tracker:

rachio:
  api_key: !secret rachio_api_key

zwave:
  usb_path: /dev/ttyACM0